### ISSUE TITLE
プログレスバーが閾値を超える度に初期化されてしまう

### ISSUE THREAD

**Issue by Im-neko** [atsukoba/reiwa_bustimer#6]
# 問題
maxSecを決定する分岐のどこかに当たるとそこでプログレスバーが初期化されてしまう．

# 現在
突然プログレスバーが初期化されるのはちょっと良くない．
応急処置としてどのバスも10分を固定でmaxSecにしている．

# 要望
このままで良ければこのままでも良いし，もし意向に添わなければrevertするのでどんな形が望ましいか教えてください!!!

**Comment by atsukoba** [comment]
そうですね，，あるいみ動作確認の意味も含めていくつかの閾値を用意していた感はあるので実際使うとなったら10分固定でいいかもしれないです！
